on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: python
          include-component-in-tag: true

      - uses: actions/checkout@v4
        if: ${{ steps.release-please.outputs.prs_created == 'true' }}
        with:
          ref: ${{ fromJson(steps.release-please.outputs.pr).headBranchName }}
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      - name: update lock file
        if: ${{ steps.release-please.outputs.prs_created == 'true' }}
        run: |
          git config user.name "release-please[bot]"
          git config user.email "release-please[bot]@users.noreply.github.com"
          pipx install uv
          uv sync
          git checkout ${{ fromJson(steps.release-please.outputs.pr).headBranchName }}
          git add .
          git commit -m "chore: update uv.lock"
          git push
